---
version: '3.8'
services:

  starcharts:
    image: starcharts:latest-alpine
    container_name: ${NAMESPACE}-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_PAGE_SIZE: ${GITHUB_PAGE_SIZE}
      PORT: ${PORT}
    volumes:
    - ./static:/opt/starcharts/static
    - ./templates:/opt/starcharts/templates
    depends_on:
    - redis
    ports:
    - 3000:3000
    networks:
    - internal
    - web       
    restart: unless-stopped
    command: ["starcharts"]

  redis:
    image: redis:6-alpine
    container_name: ${NAMESPACE}-redis
    networks:
    - internal
    volumes:
    - redis-data:/data
    restart: unless-stopped
    command:
    - "redis-server"
    - "--maxmemory 2G"
    - "--maxmemory-policy allkeys-lru"

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  redis-data:
